baseURL: "https://niccolozanotti.com" 
title: Niccolò Zanotti
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Presentations
          url: presentations/
          weight: 2 
        - name: Software
          url: software/
          weight: 2

params:
    description: "I am MSc Student in AI at unibo. Collaborator at the Institute of Computing for Climate Science in Cambridge, UK."
    author: Niccolò Zanotti
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Niccolò Zanotti
          subtitle: "I am an MSc Student in AI at <a href='https://www.unibo.it/en' style='color:#209b91;'>unibo</a>. Collaborator at the <a href='https://iccs.cam.ac.uk' style='color:#209b91;'>Institute of Computing for Climate Science</a>. Interested in Climate (sea ice), Machine Learning and Research Software."
          imageUrl: "profile.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Software
              url: software/
            - name: Presentations
              url: presentations/
            - name: Tags
              url: tags/

    socialIcons:
        # - name: CV
          # url: cv.pdf
        - name: Email
          url: mailto:contact@niccolozanotti.com
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=C4a_Q9QAAAAJ
        - name: Linkedin
          url: https://www.linkedin.com/in/niccolo-zanotti
        - name: GitHub
          url: https://github.com/niccolozanotti
        # - name: Codeberg
        #   url: https://codeberg.org/niccolozanotti
        - name: Bluesky
          url: https://bsky.app/profile/niccolozanotti.com
        - name: Mastodon
          url: https://mastodon.social/@niccolozanotti

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Niccolò Zanotti"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
